### ISSUE TITLE
a clear error in Figure 1A in your PP paper ?

### ISSUE THREAD

**Issue by Liyi56** [agolicz/lncRNAs-Plots#3]
the length of lincRNA  is over than 200bp, but 0-200bp distribution of lincRNA is include in figure1A .
I think that it should be a gap in 0-200bp in lincRNA in figure1A. right?

**Comment by agolicz** [comment]
Hi, the graph presents both coding and non-coding genes and is not limited
to lncRNAs. There are coding genes which are shorter than 200 bp, therefore
the graph will not start at 200 bp.
It's just a graphical representation which shows that lincRNAs are shorter
than protein coding genes. It is not usual for density plots to look that
way, it is not a histogram. The scale is quite small and
difficult to see. I have checked the input files and everything is in order.
This is a standard way to present this information. Please consult:
https://academic.oup.com/nar/article/45/22/e183/4282667, Figure 6.
Please do not open future issues on github. If you have any further queries
contact the corresponding author.
Hope that clears up the confusion.
Agnieszka Golicz

**Comment by Liyi56** [comment]
sorry, I have realized my mistake! I won't open new issues. but I want to explain it, the reason I opend the second issue #3 is that  I draw a picture from my data according your method, and the picture is like 
[1A.pdf](https://github.com/agolicz/lncRNAs-Plots/files/2249604/1A.pdf)
the lincRNA have the the 0-200bp ZERO horizontal line, so I think this is the correct gragh, but maybe I'am a rookie in it! at last,I am very sorry,and wish you all the best in the future!
